#!/bin/bash

#run the clab inspect command to capture the IP addresses of the nodes
output=$(clab inspect)

#parse the Name and IP address from the 2nd and 7th columns
name_and_ips=$(echo "$output" | awk -F '|' '$2 ~ /[0-9]/ {gsub(/\/24/, "", $8); print $3 "|" $8}')
#echo "$name_and_ips"

#get the tmux session name
session=$(tmux display-message -p '#S')
session=$(echo "$session" | awk '{$1=$1};1')

#loop through each
while IFS='|' read -r name ip_address; do
	#Trim leading and trailing spaces from name
	name=$(echo "$name" | awk '{$1=$1};1')
	ip_address=$(echo "$ip_address" | awk '{$1=$1};1')
	if [[ "$name" == "$session" ]]; then
		echo "Opening telnet for $name at $ip_address"
		#mux new -d -s $name
		tmux send-keys -t "$name" "telnet "$ip_address" 5000" ENTER
		break
	fi
done <<<"$name_and_ips"
