#!/bin/bash

echo "Backing up the config to main directory"

cp ./clab-sros-beanfield-lab01/bng1/tftpboot/config.txt ./CONFIGS/config-bng1.txt
cp ./clab-sros-beanfield-lab01/bng2/tftpboot/config.txt ./CONFIGS/config-bng2.txt
cp ./clab-sros-beanfield-lab01/rr1/tftpboot/config.txt ./CONFIGS/config-rr1.txt
cp ./clab-sros-beanfield-lab01/rr2/tftpboot/config.txt ./CONFIGS/config-rr2.txt
cp ./clab-sros-beanfield-lab01/spine1/tftpboot/config.txt ./CONFIGS/config-spin1.txt
cp ./clab-sros-beanfield-lab01/spine2/tftpboot/config.txt ./CONFIGS/config-spine2.txt
cp ./clab-sros-beanfield-lab01/peer1/tftpboot/config.txt ./CONFIGS/config-peer1.txt
cp ./clab-sros-beanfield-lab01/leaf1/tftpboot/config.txt ./CONFIGS/config-leaf1.txt

echo "Copy completed"

